const SIZE=5;
const stages=[
{target:8,maxMerges:3,tiles:[[2,2],[2,3],[3,2],[3,3]]},
{target:16,maxMerges:3,tiles:[[1,1,4],[1,3,4],[3,1,4],[3,3,4]]},
{target:16,maxMerges:3,tiles:[[0,0,2],[0,4,2],[2,1,4],[2,3,4],[4,2,8]]},
{target:32,maxMerges:4,tiles:[[0,1,4],[0,3,4],[2,0,8],[2,4,8],[4,1,8],[4,3,8]]},
{target:64,maxMerges:5,tiles:[[0,0,8],[0,4,8],[2,0,8],[2,4,8],[4,0,16],[4,4,16]]}
];
let stageIndex=0,board=[],merges=0,locked=false;
const boardEl=document.querySelector('#board'),stageLabel=document.querySelector('#stageLabel'),targetLabel=document.querySelector('#targetLabel'),mergeLabel=document.querySelector('#mergeLabel'),overlay=document.querySelector('#overlay'),modalKicker=document.querySelector('#modalKicker'),modalTitle=document.querySelector('#modalTitle'),modalText=document.querySelector('#modalText'),nextBtn=document.querySelector('#nextBtn');
const emptyBoard=()=>Array.from({length:SIZE},()=>Array(SIZE).fill(0));
function loadStage(index){stageIndex=index;board=emptyBoard();merges=0;locked=false;const s=stages[index];s.tiles.forEach(([r,c,v=2])=>board[r][c]=v);overlay.classList.add('hidden');render()}
function render(){const s=stages[stageIndex];stageLabel.textContent=`${stageIndex+1} / ${stages.length}`;targetLabel.textContent=s.target;mergeLabel.textContent=`${merges} / ${s.maxMerges}`;boardEl.innerHTML='';board.flat().forEach(v=>{const cell=document.createElement('div');cell.className='cell';if(v){const tile=document.createElement('div');tile.className='tile';tile.dataset.value=v;tile.textContent=v;cell.appendChild(tile)}boardEl.appendChild(cell)})}
function compressLine(line){const nums=line.filter(Boolean),result=[];let mergeCount=0;for(let i=0;i<nums.length;i++){if(nums[i]===nums[i+1]){result.push(nums[i]*2);mergeCount++;i++}else result.push(nums[i])}while(result.length<SIZE)result.push(0);return{line:result,mergeCount}}
const arraysEqual=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
function move(direction){if(locked)return;const before=board.map(r=>[...r]);let next=emptyBoard(),moveMerges=0;for(let i=0;i<SIZE;i++){let line=(direction==='left'||direction==='right')?[...board[i]]:board.map(r=>r[i]);if(direction==='right'||direction==='down')line.reverse();const compressed=compressLine(line);line=compressed.line;moveMerges+=compressed.mergeCount;if(direction==='right'||direction==='down')line.reverse();for(let j=0;j<SIZE;j++){if(direction==='left'||direction==='right')next[i][j]=line[j];else next[j][i]=line[j]}}if(arraysEqual(before,next))return;board=next;merges+=moveMerges;render();evaluate()}
function evaluate(){const s=stages[stageIndex];if(board.flat().includes(s.target)&&merges<=s.maxMerges){locked=true;showModal(true);return}if(merges>s.maxMerges){locked=true;showModal(false)}}
function showModal(clear){overlay.classList.remove('hidden');if(clear){const last=stageIndex===stages.length-1;modalKicker.textContent=last?'COMPLETE':'CLEAR';modalTitle.textContent=last?'All clear.':'Nice.';modalText.textContent=last?'プロトタイプの全ステージをクリアしました。':`ターゲット ${stages[stageIndex].target} を作りました。`;nextBtn.textContent=last?'最初から遊ぶ':'次のステージ';nextBtn.dataset.action=last?'first':'next'}else{modalKicker.textContent='OVER';modalTitle.textContent='Too many merges.';modalText.textContent=`合体は ${stages[stageIndex].maxMerges} 回まで。別の順番を試してみよう。`;nextBtn.textContent='もう一度';nextBtn.dataset.action='retry'}}
nextBtn.addEventListener('click',()=>{const a=nextBtn.dataset.action;if(a==='next')loadStage(stageIndex+1);else if(a==='first')loadStage(0);else loadStage(stageIndex)});document.querySelector('#restartBtn').addEventListener('click',()=>loadStage(stageIndex));document.querySelectorAll('[data-dir]').forEach(btn=>btn.addEventListener('click',()=>move(btn.dataset.dir)));document.addEventListener('keydown',e=>{const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'};if(map[e.key]){e.preventDefault();move(map[e.key])}});
let touchStart=null;boardEl.addEventListener('pointerdown',e=>{touchStart={x:e.clientX,y:e.clientY};boardEl.setPointerCapture?.(e.pointerId)});boardEl.addEventListener('pointerup',e=>{if(!touchStart)return;const dx=e.clientX-touchStart.x,dy=e.clientY-touchStart.y;touchStart=null;if(Math.max(Math.abs(dx),Math.abs(dy))<24)return;if(Math.abs(dx)>Math.abs(dy))move(dx>0?'right':'left');else move(dy>0?'down':'up')});loadStage(0);
